### ISSUE TITLE
Feature blocks type

### ISSUE THREAD

**Issue by alrichardbollans** [dsilvestro/npBNN#2]
https://github.com/dsilvestro/npBNN/blob/9439b0262979ccb6d84cc293129bf9284b583d62/bnn_runner.py#L96

In the example, `feature_blocks` are given as a list which, for me, raises the error: "AttributeError: 'list' object has no attribute 'keys'", as the function expects `feature_blocks` to be a `dict`

**Comment by dsilvestro** [comment]
@tandermann can you check this?

**Comment by dsilvestro** [comment]
@alrichardbollans this should be now fixed in the latest version v.0.1.14.
